server.port=9099
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=youtube-clone


####################AWS#######################
cloud.aws.region.static=eu-central-1
cloud.aws.stack.auto=false

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-izoun0x732tui83o.us.auth0.com/
auth0.audience = http://localhost:9099

